server:
  port: 8080

spring:
  application:
    name: mantra-backend

  datasource:
    url: jdbc:mysql://localhost:3306/mantra_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    user:
      password: admin

# JWT Configuration
jwt:
  secret: mantraSecretKeyForJWTTokenGeneration2024VeryLongSecretKey123456
  expiration: 86400000 # 24 hours

# Gemini API Configuration
gemini:
  api:
    key: YOUR_GEMINI_API_KEY_HERE
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

# Logging
logging:
  level:
    com.mantra: DEBUG
    org.springframework.security: DEBUG

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html